# Working with Text Data

In [1]:
import pandas as pd

## This Module's Dataset
- This module's dataset (`chicago.csv`) is a collection of public sector employees in the city of Chicago.
- Each row includes the employee's name, position, department, and salary.

In [2]:
chicago = pd.read_csv("chicago.csv").dropna(how="all")
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [3]:
chicago.info()

<class 'pandas.DataFrame'>
RangeIndex: 32062 entries, 0 to 32061
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  str
 1   Position Title          32062 non-null  str
 2   Department              32062 non-null  str
 3   Employee Annual Salary  32062 non-null  str
dtypes: str(4)
memory usage: 2.6 MB

In [4]:
chicago.nunique()

Name                      31776
Position Title             1093
Department                   35
Employee Annual Salary     1156
dtype: int64

In [5]:
chicago["Department"] = chicago["Department"].astype("category")

In [6]:
chicago.info()

<class 'pandas.DataFrame'>
RangeIndex: 32062 entries, 0 to 32061
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  str
 1   Position Title          32062 non-null  str
 2   Department              32062 non-null  category
 3   Employee Annual Salary  32062 non-null  str
dtypes: category(1), str(3)
memory usage: 2.1 MB

In [7]:
chicago = (
    pd.read_csv("chicago.csv").dropna(how="all").astype({"Department": "category"})
)
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

## Common String Methods
- A `Series` has a special `str` attribute that exposes an object with string methods.
- Access the `str` attribute, then invoke the string method on the nested object.
- Most method names will match their Python method equivalents (`upper`, `lower`, `title`, etc).

In [8]:
chicago = (
    pd.read_csv("chicago.csv").dropna(how="all").astype({"Department": "category"})
)
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [9]:
chicago["Position Title"].str.lower()
chicago["Position Title"].str.upper()
chicago["Position Title"].str.title()
chicago["Position Title"].str.len()
chicago["Position Title"].str.title().str.len()

chicago["Position Title"].str.strip()
chicago["Position Title"].str.lstrip()
chicago["Position Title"].str.rstrip()

chicago["Position Title"].str.count("A")

chicago["Department"].str.replace("MGMNT", "MANAGEMENT").str.title()

0        Water Management
1                  Police
2                  Police
3        General Services
4        Water Management
               ...
32057    General Services
32058              Police
32059              Police
32060              Police
32061                Doit
Name: Department, Length: 32062, dtype: str

- The `str` attribute exposes an object that supports square bracket syntax for indexing.
- You can provide values, slices, or negative numbers.

In [10]:
chicago["Department"].str[0]
chicago["Department"].str[3]

chicago["Department"].str[1:7]
chicago["Department"].str[0:7]
chicago["Department"].str[:7]
chicago["Department"].str[7:]

chicago["Department"].str[-1]
chicago["Department"].str[-3]

0        M
1        I
2        I
3        C
4        M
        ..
32057    C
32058    I
32059    I
32060    I
32061    o
Name: Department, Length: 32062, dtype: object

## Filtering with String Methods
- The `str.contains` method checks whether a substring exists anywhere in the string.
- The `str.startswith` method checks whether a substring exists at the start of the string.
- The `str.endswith` method checks whether a substring exists at the end of the string.

In [11]:
chicago = (
    pd.read_csv("chicago.csv").dropna(how="all").astype({"Department": "category"})
)
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [12]:
water_workers = chicago["Position Title"].str.lower().str.contains("water")
water_workers = chicago["Position Title"].str.upper().str.contains("WATER")
water_workers = chicago["Position Title"].str.contains("water", case=False)
chicago[water_workers]

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
554,"ALUISE, VINCENT G",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
671,"ANDER, PERRY A",WATER CHEMIST II,WATER MGMNT,$82044.00
685,"ANDERSON, ANDREW J",DISTRICT SUPERINTENDENT OF WATER DISTRIBUTION,WATER MGMNT,$109272.00
702,"ANDERSON, DONALD",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
...,...,...,...,...
29669,"VERMA, ANUPAM",MANAGING ENGINEER - WATER MANAGEMENT,WATER MGMNT,$111192.00
30239,"WASHINGTON, JOSEPH",WATER CHEMIST III,WATER MGMNT,$89676.00
30544,"WEST, THOMAS R",GEN SUPT OF WATER MANAGEMENT,WATER MGMNT,$115704.00
30991,"WILLIAMS, MATTHEW",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
31405,"WOODRIDGE, ROBERT L",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00

In [13]:
starts_with_civil = (
    chicago["Position Title"].str.lower().str.strip().str.startswith("civil")
)
chicago[starts_with_civil]

,Name,Position Title,Department,Employee Annual Salary
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
25,"ABDULSATTAR, MUDHAR",CIVIL ENGINEER II,WATER MGMNT,$58536.00
34,"ABRAHAM, GIRLEY T",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
55,"ABUTALEB, AHMAD H",CIVIL ENGINEER II,WATER MGMNT,$89676.00
147,"ADAMS, TANERA C",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
...,...,...,...,...
31623,"YANG, LUYANG",CIVIL ENGINEER V,TRANSPORTN,$116784.00
31656,"YEPEZ, JESUS",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
31662,"YESUFU, STEPHANIE A",CIVIL ENGINEER III,TRANSPORTN,$92784.00
31797,"ZAKE, JOSHUA S",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
31935,"ZHANG, ANNE",CIVIL ENGINEER III,TRANSPORTN,$77364.00

In [14]:
ends_with_iv = chicago["Position Title"].str.lower().str.strip().str.endswith("iv")
chicago[ends_with_iv]

,Name,Position Title,Department,Employee Annual Salary
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
34,"ABRAHAM, GIRLEY T",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
145,"ADAMS, SHERYLL A",LIBRARIAN IV,PUBLIC LIBRARY,$97812.00
147,"ADAMS, TANERA C",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
166,"ADENI, MOHAMED K",ACCOUNTANT IV,FINANCE,$97812.00
...,...,...,...,...
31777,"ZAFIRIS, CHRISTOPHER",ARCHITECT IV,DISABILITIES,$106836.00
31797,"ZAKE, JOSHUA S",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
31870,"ZAVALA, FERNANDO",ACCOUNTANT IV,FINANCE,$97812.00
31884,"ZAWADSKI, JAMES",CLERK IV,LAW,$68028.00
32008,"ZOTTA, SANDINO",MECHANICAL ENGINEER IV,WATER MGMNT,$106836.00

## String Methods on Index and Columns
- Use the `index` and `columns` attributes to access the `DataFrame` index/column labels.
- These objects support string methods via their own `str` attribute.

In [15]:
chicago = (
    pd.read_csv("chicago.csv", index_col="Name")
    .dropna(how="all")
    .astype({"Department": "category"})
)
chicago.head()

,Position Title,Department,Employee Annual Salary
Name,,,
"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [16]:
chicago.index = chicago.index.str.strip().str.title()

In [17]:
chicago.head()

,Position Title,Department,Employee Annual Salary
Name,,,
"Aaron, Elvia J",WATER RATE TAKER,WATER MGMNT,$90744.00
"Aaron, Jeffery M",POLICE OFFICER,POLICE,$84450.00
"Aaron, Karina",POLICE OFFICER,POLICE,$84450.00
"Aaron, Kimberlei R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"Abad Jr, Vicente M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [18]:
chicago.columns = chicago.columns.str.upper()

In [19]:
chicago.head()

,POSITION TITLE,DEPARTMENT,EMPLOYEE ANNUAL SALARY
Name,,,
"Aaron, Elvia J",WATER RATE TAKER,WATER MGMNT,$90744.00
"Aaron, Jeffery M",POLICE OFFICER,POLICE,$84450.00
"Aaron, Karina",POLICE OFFICER,POLICE,$84450.00
"Aaron, Kimberlei R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"Abad Jr, Vicente M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

## The str.split Method
- The `str.split` method splits a string by the occurrence of a delimiter. Pandas returns a `Series` of lists.
- Use the `str.get` method to access a nested list element by its index position.

In [20]:
chicago = (
    pd.read_csv("chicago.csv").dropna(how="all").astype({"Department": "category"})
)
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [21]:
chicago["Position Title"].str.split(" ").str.get(0).value_counts()

Position Title
POLICE             10856
FIREFIGHTER-EMT     1509
SERGEANT            1186
POOL                 918
FIREFIGHTER          810
                   ...
COMM                   1
EQUAL                  1
HATE                   1
DECK                   1
PREPRESS               1
Name: count, Length: 320, dtype: int64

- Let's find the most common first name among the employees.

In [22]:
chicago["Name"].str.title().str.split(", ").str.get(1).str.strip().str.split(
    " "
).str.get(0).value_counts()

Name
Michael    1153
John        899
James       676
Robert      622
Joseph      537
           ...
Sandino       1
Hamzeh        1
Janaan        1
Alen          1
Mac           1
Name: count, Length: 5091, dtype: int64

## The expand and n Parameters of the str.split Method
- The `expand` parameter returns a `DataFrame` instead of a `Series` of lists.
- The `n` parameter limits the number of splits.

In [23]:
chicago = (
    pd.read_csv("chicago.csv").dropna(how="all").astype({"Department": "category"})
)
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [24]:
chicago[["Last Name", "First Name"]] = (
    chicago["Name"].str.title().str.split(", ", expand=True)
)

In [25]:
chicago.head()

,Name,Position Title,Department,Employee Annual Salary,Last Name,First Name
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,Aaron,Elvia J
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,Aaron,Jeffery M
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,Aaron,Karina
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00,Aaron,Kimberlei R
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00,Abad Jr,Vicente M

In [26]:
chicago[["Primary Title", "Secondary Title"]] = (
    chicago["Position Title"].str.title().str.split(" ", expand=True, n=1)
)

In [27]:
chicago.head()

,Name,Position Title,Department,Employee Annual Salary,Last Name,First Name,Primary Title,Secondary Title
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,Aaron,Elvia J,Water,Rate Taker
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,Aaron,Jeffery M,Police,Officer
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,Aaron,Karina,Police,Officer
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00,Aaron,Kimberlei R,Chief,Contract Expediter
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00,Abad Jr,Vicente M,Civil,Engineer Iv

## The explode Method
- The `explode` method transforms a `Series` of lists into a column with a separate row for each list element.
- Pandas preserves the original index. Use `reset_index` with `drop=True` to generate a new sequential index.

In [28]:
skills = pd.read_csv("employee_skills.csv")
skills.head()

  Employee    Department              Skills
0    Alice   Engineering   Python|SQL|Docker
1      Bob   Engineering       Java|Python|R
2    Carol  Data Science                 SQL
3    David  Data Science  Python|SQL|Tableau
4     Emma   Engineering   Python|JavaScript

In [29]:
skills["Skills"] = skills["Skills"].str.split("|")
skills.head()

  Employee    Department                  Skills
0    Alice   Engineering   [Python, SQL, Docker]
1      Bob   Engineering       [Java, Python, R]
2    Carol  Data Science                   [SQL]
3    David  Data Science  [Python, SQL, Tableau]
4     Emma   Engineering    [Python, JavaScript]

In [30]:
skills.explode("Skills").reset_index(drop=True)

   Employee    Department      Skills
0     Alice   Engineering      Python
1     Alice   Engineering         SQL
2     Alice   Engineering      Docker
3       Bob   Engineering        Java
4       Bob   Engineering      Python
5       Bob   Engineering           R
6     Carol  Data Science         SQL
7     David  Data Science      Python
8     David  Data Science         SQL
9     David  Data Science     Tableau
10     Emma   Engineering      Python
11     Emma   Engineering  JavaScript
12    Frank  Data Science           R
13    Frank  Data Science      Python
14    Frank  Data Science         SQL