# Options and Settings

In [1]:
import pandas as pd

## Changing Options with Attributes
- The `pd.options` module configures Pandas's settings.
- The `display` module deals with the presentation of data.

In [2]:
spotify = pd.read_csv("spotify.csv")
spotify.head()

,Track,Artist,Album,Genre,Duration (min),Tempo (BPM),Energy,Danceability,Loudness (dB),Popularity,Streams (M)
0,Roads,The Midnight Drift,The Landscapes,R&B,3.74,105.4,0.5390,0.5747,-7.43,52,74.21
1,The Horizon of Nowhere,Starfall Collective,The Archives,R&B,3.82,76.9,0.4047,0.8809,-6.85,49,15.44
2,Sky Away,Sam Kariuki,Songs from the Underground,Pop,3.04,130.7,0.6967,0.7497,-6.25,67,253.67
3,Only Sunrise,Andre Laurent,The Territories,Rock,3.35,156.7,0.8623,0.5503,-8.31,72,10.00
4,Storm,The Broken Compass,The Chapters,Rock,2.77,153.5,0.7548,0.3262,-2.08,61,90.17

- The `max_rows` attribute sets the threshold/limit where the `DataFrame` rows will be truncated.
- The `min_rows` attribute sets the minimum number of displayed rows when `max_rows` is exceeded.
- Overwrite an attribute's value with an equal sign and the new value.

In [3]:
pd.options.display.max_rows
pd.options.display.min_rows

10

In [4]:
pd.options.display.min_rows = 14

In [5]:
spotify

,Track,Artist,Album,Genre,Duration (min),Tempo (BPM),Energy,Danceability,Loudness (dB),Popularity,Streams (M)
0,Roads,The Midnight Drift,The Landscapes,R&B,3.74,105.4,0.5390,0.5747,-7.43,52,74.21
1,The Horizon of Nowhere,Starfall Collective,The Archives,R&B,3.82,76.9,0.4047,0.8809,-6.85,49,15.44
2,Sky Away,Sam Kariuki,Songs from the Underground,Pop,3.04,130.7,0.6967,0.7497,-6.25,67,253.67
3,Only Sunrise,Andre Laurent,The Territories,Rock,3.35,156.7,0.8623,0.5503,-8.31,72,10.00
4,Storm,The Broken Compass,The Chapters,Rock,2.77,153.5,0.7548,0.3262,-2.08,61,90.17
5,Horizon,Pacific Gold,The Passages,Hip-Hop,3.37,83.5,0.8791,0.9195,-4.72,66,57.09
6,Silence,Omar Hassan,The Passages,Pop,1.84,120.2,0.6585,0.6766,-3.91,87,156.60
...,...,...,...,...,...,...,...,...,...,...,...
193,Hearts Tonight,Solstice,The Horizons,Pop,2.34,109.8,0.7621,0.6972,-6.54,49,1.00
194,Silver Garden,Yuki Tanaka,The Echoes,Pop,3.45,118.1,0.6259,0.5463,-3.93,63,238.78
195,Waiting in the Sky,Nina Volkov,Chapters Vol. 2,Rock,3.73,152.4,0.9308,0.5013,-4.80,59,49.02
196,Waves Again,Luna Torres,Songs from the Edge of the World,Hip-Hop,2.88,67.6,0.7090,0.7991,-5.96,35,0.10
197,The Roads of Tomorrow,Sofia Vega,The Echoes,Rock,4.87,104.3,0.7052,0.4378,-1.00,84,930.03
198,Another Sunrise,The Wandering Suns,The Territories,Latin,2.60,118.6,0.7875,0.6610,-5.40,72,211.98
199,Silence Again,Luna Torres,Songs from the Edge of the World,Pop,4.64,103.4,0.7720,0.7726,-4.00,71,195.37

- The `max_columns` attribute sets the threshold/limit where the `DataFrame` columns will be truncated.

In [6]:
pd.options.display.max_columns

20

In [7]:
pd.options.display.max_columns = 6

In [8]:
spotify.head()

,Track,Artist,Album,...,Loudness (dB),Popularity,Streams (M)
0,Roads,The Midnight Drift,The Landscapes,...,-7.43,52,74.21
1,The Horizon of Nowhere,Starfall Collective,The Archives,...,-6.85,49,15.44
2,Sky Away,Sam Kariuki,Songs from the Underground,...,-6.25,67,253.67
3,Only Sunrise,Andre Laurent,The Territories,...,-8.31,72,10.00
4,Storm,The Broken Compass,The Chapters,...,-2.08,61,90.17

## Changing Options with Functions
- The `pd.get_option` function retrieves the current value for a pandas setting.
- The `pd.set_option` function sets a new value for a pandas setting.
- The `pd.describe_option` function provides documentation for a pandas setting.
- The `pd.reset_option` function returns a pandas setting back to its default value.

In [9]:
spotify = pd.read_csv("spotify.csv")
spotify.head(1)

,Track,Artist,Album,...,Loudness (dB),Popularity,Streams (M)
0,Roads,The Midnight Drift,The Landscapes,...,-7.43,52,74.21

In [10]:
pd.options.display.min_rows

14

In [11]:
pd.get_option("display.min_rows")
pd.get_option("display.max_rows")
pd.get_option("display.max_columns")

6

In [12]:
pd.set_option("display.min_rows", 14)
pd.set_option("display.max_columns", 6)

In [13]:
pd.describe_option("display.max_rows")

display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view.

    'None' value means unlimited. Beware that printing a large number of rows
    could cause your rendering environment (the browser, etc.) to crash.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 60]

In [14]:
pd.reset_option("display.min_rows")
pd.reset_option("display.max_rows")
pd.reset_option("display.max_columns")

In [15]:
spotify

,Track,Artist,Album,Genre,Duration (min),Tempo (BPM),Energy,Danceability,Loudness (dB),Popularity,Streams (M)
0,Roads,The Midnight Drift,The Landscapes,R&B,3.74,105.4,0.5390,0.5747,-7.43,52,74.21
1,The Horizon of Nowhere,Starfall Collective,The Archives,R&B,3.82,76.9,0.4047,0.8809,-6.85,49,15.44
2,Sky Away,Sam Kariuki,Songs from the Underground,Pop,3.04,130.7,0.6967,0.7497,-6.25,67,253.67
3,Only Sunrise,Andre Laurent,The Territories,Rock,3.35,156.7,0.8623,0.5503,-8.31,72,10.00
4,Storm,The Broken Compass,The Chapters,Rock,2.77,153.5,0.7548,0.3262,-2.08,61,90.17
...,...,...,...,...,...,...,...,...,...,...,...
195,Waiting in the Sky,Nina Volkov,Chapters Vol. 2,Rock,3.73,152.4,0.9308,0.5013,-4.80,59,49.02
196,Waves Again,Luna Torres,Songs from the Edge of the World,Hip-Hop,2.88,67.6,0.7090,0.7991,-5.96,35,0.10
197,The Roads of Tomorrow,Sofia Vega,The Echoes,Rock,4.87,104.3,0.7052,0.4378,-1.00,84,930.03
198,Another Sunrise,The Wandering Suns,The Territories,Latin,2.60,118.6,0.7875,0.6610,-5.40,72,211.98
199,Silence Again,Luna Torres,Songs from the Edge of the World,Pop,4.64,103.4,0.7720,0.7726,-4.00,71,195.37

## The precision Option
- The `display.precision` option sets the number of digits that appears after a decimal point in a floating-point number.
- The default value is 6.

In [16]:
spotify = pd.read_csv("spotify.csv")
spotify.head()

,Track,Artist,Album,Genre,Duration (min),Tempo (BPM),Energy,Danceability,Loudness (dB),Popularity,Streams (M)
0,Roads,The Midnight Drift,The Landscapes,R&B,3.74,105.4,0.5390,0.5747,-7.43,52,74.21
1,The Horizon of Nowhere,Starfall Collective,The Archives,R&B,3.82,76.9,0.4047,0.8809,-6.85,49,15.44
2,Sky Away,Sam Kariuki,Songs from the Underground,Pop,3.04,130.7,0.6967,0.7497,-6.25,67,253.67
3,Only Sunrise,Andre Laurent,The Territories,Rock,3.35,156.7,0.8623,0.5503,-8.31,72,10.00
4,Storm,The Broken Compass,The Chapters,Rock,2.77,153.5,0.7548,0.3262,-2.08,61,90.17

In [17]:
pd.options.display.precision

6

In [18]:
pd.get_option("display.precision")

6

In [19]:
pd.options.display.precision = 2

In [20]:
pd.set_option("display.precision", 2)

In [21]:
spotify.head()

,Track,Artist,Album,Genre,Duration (min),Tempo (BPM),Energy,Danceability,Loudness (dB),Popularity,Streams (M)
0,Roads,The Midnight Drift,The Landscapes,R&B,3.74,105.4,0.54,0.57,-7.43,52,74.21
1,The Horizon of Nowhere,Starfall Collective,The Archives,R&B,3.82,76.9,0.40,0.88,-6.85,49,15.44
2,Sky Away,Sam Kariuki,Songs from the Underground,Pop,3.04,130.7,0.70,0.75,-6.25,67,253.67
3,Only Sunrise,Andre Laurent,The Territories,Rock,3.35,156.7,0.86,0.55,-8.31,72,10.00
4,Storm,The Broken Compass,The Chapters,Rock,2.77,153.5,0.75,0.33,-2.08,61,90.17

In [22]:
spotify["Danceability"].iloc[0]

np.float64(0.5747)

## Temporary Options with option_context
- The `pd.option_context` context manager temporarily changes options within a `with` block.
- Options revert back to their default values when the block ends.
- Pass a dictionary where the keys are the settings and the values are their temporary values.
- Use the `display` function to output the `DataFrame`.

In [23]:
pd.reset_option("display.max_rows")
pd.reset_option("display.max_rows")
pd.reset_option("display.max_columns")
pd.reset_option("display.precision")

In [24]:
spotify = pd.read_csv("spotify.csv")
spotify

,Track,Artist,Album,Genre,Duration (min),Tempo (BPM),Energy,Danceability,Loudness (dB),Popularity,Streams (M)
0,Roads,The Midnight Drift,The Landscapes,R&B,3.74,105.4,0.5390,0.5747,-7.43,52,74.21
1,The Horizon of Nowhere,Starfall Collective,The Archives,R&B,3.82,76.9,0.4047,0.8809,-6.85,49,15.44
2,Sky Away,Sam Kariuki,Songs from the Underground,Pop,3.04,130.7,0.6967,0.7497,-6.25,67,253.67
3,Only Sunrise,Andre Laurent,The Territories,Rock,3.35,156.7,0.8623,0.5503,-8.31,72,10.00
4,Storm,The Broken Compass,The Chapters,Rock,2.77,153.5,0.7548,0.3262,-2.08,61,90.17
...,...,...,...,...,...,...,...,...,...,...,...
195,Waiting in the Sky,Nina Volkov,Chapters Vol. 2,Rock,3.73,152.4,0.9308,0.5013,-4.80,59,49.02
196,Waves Again,Luna Torres,Songs from the Edge of the World,Hip-Hop,2.88,67.6,0.7090,0.7991,-5.96,35,0.10
197,The Roads of Tomorrow,Sofia Vega,The Echoes,Rock,4.87,104.3,0.7052,0.4378,-1.00,84,930.03
198,Another Sunrise,The Wandering Suns,The Territories,Latin,2.60,118.6,0.7875,0.6610,-5.40,72,211.98
199,Silence Again,Luna Torres,Songs from the Edge of the World,Pop,4.64,103.4,0.7720,0.7726,-4.00,71,195.37

In [25]:
with pd.option_context({"display.precision": 3, "display.max_columns": 4}):
    display(spotify)

                      Track               Artist  ... Popularity Streams (M)
0                     Roads   The Midnight Drift  ...         52       74.21
1    The Horizon of Nowhere  Starfall Collective  ...         49       15.44
2                  Sky Away          Sam Kariuki  ...         67      253.67
3              Only Sunrise        Andre Laurent  ...         72       10.00
4                     Storm   The Broken Compass  ...         61       90.17
..                      ...                  ...  ...        ...         ...
195      Waiting in the Sky          Nina Volkov  ...         59       49.02
196             Waves Again          Luna Torres  ...         35        0.10
197   The Roads of Tomorrow           Sofia Vega  ...         84      930.03
198         Another Sunrise   The Wandering Suns  ...         72      211.98
199           Silence Again          Luna Torres  ...         71      195.37

[200 rows x 11 columns]

In [26]:
spotify

,Track,Artist,Album,Genre,Duration (min),Tempo (BPM),Energy,Danceability,Loudness (dB),Popularity,Streams (M)
0,Roads,The Midnight Drift,The Landscapes,R&B,3.74,105.4,0.5390,0.5747,-7.43,52,74.21
1,The Horizon of Nowhere,Starfall Collective,The Archives,R&B,3.82,76.9,0.4047,0.8809,-6.85,49,15.44
2,Sky Away,Sam Kariuki,Songs from the Underground,Pop,3.04,130.7,0.6967,0.7497,-6.25,67,253.67
3,Only Sunrise,Andre Laurent,The Territories,Rock,3.35,156.7,0.8623,0.5503,-8.31,72,10.00
4,Storm,The Broken Compass,The Chapters,Rock,2.77,153.5,0.7548,0.3262,-2.08,61,90.17
...,...,...,...,...,...,...,...,...,...,...,...
195,Waiting in the Sky,Nina Volkov,Chapters Vol. 2,Rock,3.73,152.4,0.9308,0.5013,-4.80,59,49.02
196,Waves Again,Luna Torres,Songs from the Edge of the World,Hip-Hop,2.88,67.6,0.7090,0.7991,-5.96,35,0.10
197,The Roads of Tomorrow,Sofia Vega,The Echoes,Rock,4.87,104.3,0.7052,0.4378,-1.00,84,930.03
198,Another Sunrise,The Wandering Suns,The Territories,Latin,2.60,118.6,0.7875,0.6610,-5.40,72,211.98
199,Silence Again,Luna Torres,Songs from the Edge of the World,Pop,4.64,103.4,0.7720,0.7726,-4.00,71,195.37